package org.openlobster.olbs;

/**
 * Created by view on 26/5/15.
 */
public enum OLBSConfigType {

    OLBS_BEACON_BACKGROUND_BETWEEN_SCAN_PERIOD,
    OLBS_BEACON_FOREGROUND_BETWEEN_SCAN_PERIOD,
    OLBS_BEACON_BACKGROUND_SCAN_PERIOD,
    OLBS_BEACON_FOREGROUND_SCAN_PERIOD,
    OLBS_LOCATION_UPDATE_INTERVAL_IN_MILLISECONDS,
    OLBS_LOCATION_FASTEST_UPDATE_INTERVAL_IN_MILLISECONDS,
    OLBS_SCANLOG_URL,
    OLBS_SCANLOG_LOC_LABEL,
    OLBS_USER_TOKEN,
    OLBS_USER_API_KEY,
    OLBS_HTTP_CONNECTION_TIMEOUT,
    OLBS_SOCKET_CONNECTION_TIMEOUT;

}
